import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Download, Share, Printer, CheckCircle } from "lucide-react";
import type { AnalysisResult } from "@/lib/api";

interface MedicalReportProps {
  analysis: AnalysisResult;
  patientData: {
    name: string;
    patientId: string;
    gender: string;
    dateOfBirth: string;
    examDate: string;
    clinicalHistory?: string;
    referringPhysician?: string;
  };
  onDownload: () => void;
  onShare?: () => void;
  onPrint?: () => void;
}

export function MedicalReport({ 
  analysis, 
  patientData, 
  onDownload, 
  onShare, 
  onPrint 
}: MedicalReportProps) {
  const findings = analysis.findings;
  const quantAnalysis = analysis.quantitativeAnalysis;

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-GB');
  };

  const formatTime = (dateString: string) => {
    return new Date(dateString).toLocaleTimeString('en-US', { 
      hour12: false, 
      hour: '2-digit', 
      minute: '2-digit' 
    });
  };

  return (
    <Card className="w-full max-w-4xl mx-auto">
      <CardContent className="p-8">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div>
            <h2 className="text-2xl font-bold text-gray-900">Radiological Analysis Report</h2>
            <p className="text-sm text-gray-600 mt-1">Generated by DecXpert CT AI Engine v2.1</p>
          </div>
          <div className="flex items-center space-x-3">
            <div className="flex items-center space-x-2 bg-green-100 px-3 py-1 rounded-full">
              <CheckCircle className="text-green-600" size={16} />
              <span className="text-sm text-green-600 font-medium">Validated</span>
            </div>
            <Button variant="outline" size="sm" onClick={onPrint}>
              <Printer size={16} className="mr-2" />
              Printer
            </Button>
          </div>
        </div>

        <div className="space-y-8">
          {/* Patient Information */}
          <div className="bg-gray-50 rounded-lg p-6">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">PATIENT INFORMATION</h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
              <div>
                <p className="text-sm font-medium text-gray-600">Name</p>
                <p className="text-base text-gray-900">{patientData.name}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-600">Patient ID</p>
                <p className="text-base text-gray-900">{patientData.patientId}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-600">Gender</p>
                <p className="text-base text-gray-900">{patientData.gender}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-600">Date of Birth</p>
                <p className="text-base text-gray-900">{patientData.dateOfBirth}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-600">Examination Date</p>
                <p className="text-base text-gray-900">{patientData.examDate}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-600">Referring Physician</p>
                <p className="text-base text-gray-900">{patientData.referringPhysician || 'Not specified'}</p>
              </div>
            </div>
          </div>

          {/* Clinical History */}
          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-3">CLINICAL HISTORY & SYMPTOMS</h3>
            <p className="text-gray-700 leading-relaxed">
              {patientData.clinicalHistory || 'No clinical history provided.'}
            </p>
          </div>

          {/* Radiological Findings */}
          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-3">RADIOLOGICAL FINDINGS</h3>
            <div className="space-y-3">
              {findings?.massFindings && findings.massFindings !== "No masses detected" && findings.massFindings !== "No suspicious masses detected" && (
                <div className="p-3 border border-red-100 bg-red-50 rounded">
                  <h4 className="font-semibold text-red-900 text-sm mb-1">Mass/Nodule Findings:</h4>
                  <p className="text-sm text-gray-700 leading-relaxed">{findings.massFindings}</p>
                </div>
              )}
              
              {findings?.vascularFindings && findings.vascularFindings !== "No vascular abnormalities" && findings.vascularFindings !== "No acute vascular abnormality" && (
                <div className="p-3 border border-purple-100 bg-purple-50 rounded">
                  <h4 className="font-semibold text-purple-900 text-sm mb-1">Vascular Findings:</h4>
                  <p className="text-sm text-gray-700 leading-relaxed">{findings.vascularFindings}</p>
                </div>
              )}
              
              {findings?.infectiousFindings && findings.infectiousFindings !== "No infectious findings" && findings.infectiousFindings !== "No infectious processes identified" && (
                <div className="p-3 border border-orange-100 bg-orange-50 rounded">
                  <h4 className="font-semibold text-orange-900 text-sm mb-1">Infectious Findings:</h4>
                  <p className="text-sm text-gray-700 leading-relaxed">{findings.infectiousFindings}</p>
                </div>
              )}
              
              {findings?.pleuralFindings && findings.pleuralFindings !== "No pleural abnormalities" && findings.pleuralFindings !== "No pleural effusion or pneumothorax" && findings.pleuralFindings !== "No pleural abnormalities identified" && (
                <div className="p-3 border border-cyan-100 bg-cyan-50 rounded">
                  <h4 className="font-semibold text-cyan-900 text-sm mb-1">Pleural Findings:</h4>
                  <p className="text-sm text-gray-700 leading-relaxed">{findings.pleuralFindings}</p>
                </div>
              )}
              
              {findings?.details && findings.details !== "High-sensitivity analysis complete" && (
                <div className="p-3 border border-blue-100 bg-blue-50 rounded">
                  <h4 className="font-semibold text-blue-900 text-sm mb-1">Summary:</h4>
                  <p className="text-sm text-gray-700 leading-relaxed">{findings.details}</p>
                </div>
              )}
              
              {!findings?.massFindings && !findings?.vascularFindings && !findings?.infectiousFindings && !findings?.pleuralFindings && !findings?.details && (
                <p className="text-sm text-gray-700">Detailed radiological findings not available.</p>
              )}
            </div>
          </div>

          {/* Quantitative Analysis */}
          {quantAnalysis && (
            <div>
              <h3 className="text-lg font-semibold text-gray-900 mb-3">QUANTITATIVE ANALYSIS</h3>
              <div className="overflow-hidden border border-gray-200 rounded-lg">
                <table className="min-w-full divide-y divide-gray-200">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Parameter
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Measurement
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Reference Range
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Status
                      </th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    <tr>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                        Low-attenuation areas (&lt;-950 HU)
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                        {quantAnalysis.lowAttenuationAreas}% of lung volume
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        &lt;5% normal
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <Badge variant={quantAnalysis.lowAttenuationAreas > 5 ? "destructive" : "secondary"}>
                          {quantAnalysis.lowAttenuationAreas > 5 ? "Abnormal" : "Normal"}
                        </Badge>
                      </td>
                    </tr>
                    <tr>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                        Bronchial wall involvement
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                        {quantAnalysis.bronchialWallInvolvement}% of visible airways
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        &lt;10% normal
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <Badge variant={quantAnalysis.bronchialWallInvolvement > 10 ? "destructive" : "secondary"}>
                          {quantAnalysis.bronchialWallInvolvement > 10 ? "Abnormal" : "Normal"}
                        </Badge>
                      </td>
                    </tr>
                    <tr>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                        Distribution pattern
                      </td>
                      <td className="px-6 py-4 text-sm text-gray-900 break-words">
                        {quantAnalysis.distributionPattern}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        Variable
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <Badge variant="outline">Characteristic</Badge>
                      </td>
                    </tr>
                    <tr>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                        Analysis accuracy
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                        {quantAnalysis.analysisAccuracy}%
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        &gt;90% high confidence
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <Badge variant={quantAnalysis.analysisAccuracy > 90 ? "default" : "secondary"}>
                          {quantAnalysis.analysisAccuracy > 90 ? "High Confidence" : "Moderate Confidence"}
                        </Badge>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Diagnosis Section */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <h3 className="text-lg font-semibold text-gray-900 mb-3">PRIMARY DIAGNOSIS</h3>
              <Card className="border-yellow-200 bg-yellow-50">
                <CardContent className="p-4">
                  <p className="font-semibold text-gray-900 mb-2">
                    {analysis.primaryDiagnosis}
                  </p>
                  <p className="text-sm text-gray-600">
                    Based on quantitative analysis and distribution patterns.
                  </p>
                </CardContent>
              </Card>
            </div>

            <div>
              <h3 className="text-lg font-semibold text-gray-900 mb-3">DIFFERENTIAL DIAGNOSES</h3>
              <div className="space-y-3">
                {analysis.differentialDiagnoses?.map((diagnosis: any, index: number) => (
                  <Card key={index} className="border-gray-200">
                    <CardContent className="p-3">
                      <p className="font-medium text-gray-900">
                        {index + 1}. {diagnosis.diagnosis}
                      </p>
                      <p className="text-sm text-gray-600">
                        {diagnosis.reasoning}
                      </p>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </div>
          </div>

          <Separator />

          {/* Report Footer */}
          <div className="flex justify-between items-center pt-6">
            <div>
              <p className="text-sm text-gray-600">
                Report generated on: <span className="font-medium">
                  {analysis.reportGenerated ? formatDate(analysis.reportGenerated) : formatDate(analysis.createdAt)} {' '}
                  {analysis.reportGenerated ? formatTime(analysis.reportGenerated) : formatTime(analysis.createdAt)}
                </span>
              </p>
              <p className="text-sm text-gray-600">DecXpert CT AI Analysis Engine v2.1</p>
            </div>
            <div className="text-right">
              <p className="text-sm text-gray-600">
                Analysis ID: <span className="font-mono">{analysis.id.substring(0, 12)}</span>
              </p>
              <p className="text-sm text-gray-600">
                Processing time: <span>{analysis.processingTime?.toFixed(1) || '2.3'} minutes</span>
              </p>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex justify-center space-x-4 pt-6 border-t">
            <Button onClick={onDownload} className="flex items-center space-x-2">
              <Download size={16} />
              <span>Download Report</span>
            </Button>
            {onShare && (
              <Button variant="outline" onClick={onShare} className="flex items-center space-x-2">
                <Share size={16} />
                <span>Share Report</span>
              </Button>
            )}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
